osscameroon/jobsika

- .github/workflows/backend-e2etest.yaml
- .github/workflows/backend-lint.yaml
- .github/workflows/backend-test.yaml
- backend/docker-compose.test.yml
This pull request add several backend github actions checks
Why ?
To validate pull request changes
How ?
It adds the github actions listed bellow:
The github actions should be triggered on pull request against the main branch.
> chore: add backend checks

- .github/workflows/backend-build-api-image.yaml
This pull request adds a GitHub Action workflow to build and push the api image to ghcr.
> chore: add api build image workflow

- backend/pkg/models/v1beta/salaries.go
This pull request add the `id` field to the GET salaries response
> feat: add id field to salaries GET endpoint response

- backend/e2etests/salaries.test.js
> fix: fix end to end test

- backend/e2etests/company_ratings.test.js
- backend/fixtures/postgres/sql/company_ratings.sql
- backend/internal/handlers/company_ratings_handler.go
- backend/internal/storage/company_ratings.go
- backend/main.go
- backend/migrations/20211019221200_init_db.sql
- backend/pkg/models/v1beta/company_ratings.go
- backend/scripts/setup-postgres/sql_file_ordered.txt
This pull request add the GET company rating endpoint
- then run the command `curl -X GET localhost:7000/company-ratings` you should see something like this
```
[{"id":1,"company_id":761,"rating":4,"comment":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","createdat":"0001-01-01T00:00:00Z","updatedat":"0001-01-01T00:00:00Z"},{"id":2,"company_id":995,"rating":4,"comment":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in …
```
> Add company rating endpoint

- README.md
- backend/Makefile
- backend/docs/companies.go
- backend/docs/company_ratings.go
- backend/docs/docs.go
- backend/docs/health.go
- backend/docs/salaries.go
- backend/docs/seniority.go
- backend/go.mod
- backend/go.sum
- backend/internal/handlers/companies_handler.go
- backend/internal/handlers/company_ratings_handler.go
- backend/internal/handlers/health_handler.go
- backend/internal/handlers/salaries_handler.go
- backend/main.go
- backend/swagger.yaml
This pull request add api documentation to the application
- then run `make server-swagger` and play around with the endpoints
** Screenshots
> Add swagger

- backend/docker-compose.yml
> Docker config

- frontend/components/Button.vue
- frontend/components/Company.vue
- frontend/components/Header.vue
- frontend/components/Pagination.vue
- frontend/components/Select.vue
- frontend/components/Title.vue
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/index.vue
- frontend/tailwind.config.js
- frontend/yarn.lock
add static pagination design and implementation of the responsive page
https://user-images.githubusercontent.com/34966088/150640129-d0529858-35b7-416c-9727-e8f1d8f0c34b.mp4
https://user-images.githubusercontent.com/34966088/150626873-1b3d0ae9-2820-444a-819a-6e797619fa46.mp4
> Responsive home

- frontend/components/Average.vue
- frontend/components/Company.vue
- frontend/pages/index.vue
- mobile view 
- laptop view
- web view
> BarAverageSalary: Setting up the average salary bar

- frontend/components/Company.vue
> RatingDetail: When we click on detail, we display the details of a rating

- frontend/.gitignore
- frontend/.nuxt/App.js
- frontend/.nuxt/layouts/default.vue
- frontend/.nuxt/views/app.template.html
- frontend/layouts/app.vue
- frontend/pages/add_salary.vue
- frontend/pages/index.vue
I created another layout and referenced my other pages in the new layout.
So I no longer use the default layout because every time when I build, it resets
> FixLayout: I created a new layout and reference my other pages

- frontend/components/Select.vue
https://user-images.githubusercontent.com/34966088/153133852-3cb57ce0-3ace-4d42-9a5b-a3aa3b8a96da.mp4
> JobTitles: Implementation of job title endpoints

- frontend/components/Average.vue
- frontend/pages/index.vue
> AverageRating: Implementation of average-rating endpoints

- frontend/layouts/app.vue
> RemoveTopBar: I removed the search bar

- frontend/components/Company.vue
> RemoveThePositionColumn: I deleted the position column

- frontend/components/Company.vue
> Add the seniority column

- frontend/components/Company.vue
> Add the city column

- frontend/components/Company.vue
> Use the actual date field

- frontend/components/Company.vue
- frontend/pages/add_salary.vue
> Add a city field

- frontend/components/InputAutoCompletion.vue
- frontend/components/JobTitleAutoCompletion.vue
- frontend/pages/add_salary.vue
> Implement auto completion

- frontend/components/InputAutoCompletion.vue
- frontend/pages/add_salary.vue
> CityImplementAutoCompletion: Add the auto completion on the field

- frontend/pages/add_salary.vue
> SenioritySelect: Implementation of select and autocompletion

- frontend/components/Company.vue
- frontend/components/Pagination.vue
- frontend/store/index.js
- frontend/store/ratings.js
This pull request manage the pagination so that a user can jump to a specific page.
**Screenshots**
https://user-images.githubusercontent.com/49993443/153953906-a9679031-bbb8-487d-9a88-4a0ac732e081.mp4
> Manage page

- frontend/components/Company.vue
- frontend/components/Pagination.vue
- frontend/store/index.js
- frontend/store/ratings.js
- frontend/tailwind.config.js
https://user-images.githubusercontent.com/34966088/154061256-566ac153-c3b5-4577-8d21-2e58228e868a.mp4
> Button to jump first and last page

- frontend/components/Company.vue
- frontend/components/Pagination.vue
- frontend/store/index.js
- frontend/store/ratings.js
- frontend/tailwind.config.js
https://user-images.githubusercontent.com/34966088/154000369-c7b089de-a770-4023-b761-a2caef65226d.mp4
> Highlight the current page

- backend/.docker-env
- backend/docker-compose.yml
This pull request  is a fix for the `make start-api` target
> feat: fix api docker compose config

- frontend/components/InputAutoCompletion.vue
- frontend/components/MyInput.vue
- frontend/pages/add_salary.vue
- frontend/store/index.js
- frontend/store/ratings.js
https://user-images.githubusercontent.com/34966088/154643120-19c01221-88fc-41c1-94c8-e6f4a228b1b9.mp4
> Integration of ratings post

- frontend/components/MyInput.vue
- frontend/pages/add_salary.vue
> Add fcfa currency

- frontend/components/Company.vue
- frontend/components/Error.vue
- frontend/components/Pagination.vue
- frontend/components/Select.vue
- frontend/store/index.js
- frontend/store/ratings.js
https://user-images.githubusercontent.com/34966088/154838025-8e8ecf97-2304-4142-be8d-4c72972d46c9.mp4
> FiltersListOfRatings: Implement filters on the list of ratings

- frontend/.env.example
- frontend/nuxt.config.js
- frontend/store/index.js
- frontend/utils/config.js
Setting up the environment variable
> TheBackendURLShouldComeFromAnEnvironment

- frontend/nuxt.config.js
This pull request set webiste Jobtitle to Jobsika
> Set Website title to Jobsika

- frontend/components/Pagination.vue
- frontend/tailwind.config.js
https://user-images.githubusercontent.com/34966088/155899543-fd616a18-fbce-4ac5-b70c-982a3ae5d22e.mp4
> ThePaginationOnMobile: Design for the pagination on mobile.

- frontend/components/Select.vue
https://user-images.githubusercontent.com/34966088/155527594-2bdff89d-b705-447a-a83c-ae2d2eb7ac62.mp4
> FixPaginationBugWithFilter: Set initial page to 1 when filtering

- frontend/plugins/filters.js
https://user-images.githubusercontent.com/34966088/155951280-dfb8c7fc-a4fe-40a5-8dea-e0645badb7fc.mp4
> FixBugPostRatingWithAddingAThousandSeparator: add the default of value

- frontend/components/Select.vue
- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/156074123-05114e74-d834-412b-a4e5-fa35718bcbe2.mp4
> Styling of the add salary page

- frontend/package-lock.json
Try to fix errors related to frontend [builds](https://github.com/osscameroon/camerdevs/runs/5723291867?check_suite_focus=true)
> fix-frontend-build

- backend/e2etests/ratings.test.after.js
- backend/internal/storage/ratings.go
Format the CompanyName and JobTitle on post ratings
Why ?
Refer to issue #88 
How ?
format all the string with ToLower and then with Title funcs in packages strings
N/A
> feat(backend): format the CompanyName and JobTitle on post ratings

- frontend/components/tooltip.component.vue
- frontend/pages/add_salary.vue
- frontend/tailwind.config.js
https://user-images.githubusercontent.com/34966088/162325248-669b779a-88f9-4253-ad52-68370b0b24e7.mp4
> AddTooltipButtonThatOpensAModal: added buttons to trigger the modal

- frontend/components/Company.vue
- frontend/components/Title.vue
https://user-images.githubusercontent.com/34966088/162592106-fe8d6a38-56b0-4e55-b738-54e8808a4488.mp4
> Implementing the tooltip anonymous

- frontend/components/Company.vue
https://user-images.githubusercontent.com/34966088/162574642-219e591c-cc86-454c-a2a2-445a87b52fc0.mp4
> disable detail button if is empty

- frontend/components/Title.vue
- frontend/pages/add_salary.vue
- frontend/pages/index.vue
https://user-images.githubusercontent.com/34966088/162614797-272f5c2e-8581-4be7-8c82-06a4abb95c17.mp4
> update the tooltip of title

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/162641417-f1449c52-0a3f-4542-9282-50aa6edd87e5.mp4
> update the design of tooltip

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/162729155-79a63264-09cb-4259-ac6b-7e3149c71700.mp4
> Add validation to the contribution page

- frontend/components/Company.vue
> Replace 'company names' with 'A local company'

- frontend/components/Company.vue
> Replace 'job title' with 'A job title' if field is empty

- frontend/components/StarRating.vue
- frontend/components/notification.vue
- frontend/pages/add_salary.vue
> Add an asterisk

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164586567-6fc41a03-6aa1-4443-82dd-a3f369ecd96b.mp4
> set the ratings not mandatory

- frontend/pages/add_salary.vue
> fix the html bug

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164934253-e4fc3dc2-e652-448e-a460-674d7af1331e.mp4
> Reduce the lenght of the fields

- frontend/pages/add_salary.vue
> remove an asterisk and fix select html

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164934644-908e38e3-5dd0-478a-8206-bdb1b17a4b22.mp4
> Increase font size of input titles

- frontend/components/StarRating.vue
- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164936394-7892a417-e371-4bfe-8cff-84c3e7f96b62.mp4
> Position rating before comments

- frontend/components/Button.vue
- frontend/components/StarRating.vue
- frontend/pages/add_salary.vue
> Primary btn border

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164970053-a79a1c94-ffdd-4a2a-8f90-7c6493af8849.mp4
> update text of company and seniority

- frontend/components/StarRating.vue
- frontend/components/notification.vue
- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/164971150-1b523e62-07c6-4468-97e9-de20ecb4860f.mp4
> Update anatomy of the input field

- frontend/components/Title.vue
https://user-images.githubusercontent.com/34966088/164984625-f2bb824c-a33a-41d7-a5f6-52c4a4a8e9b0.mp4
> Update description on the home screen

- frontend/components/Title.vue
> Update description on the home screen of mobile

- frontend/pages/add_salary.vue
> Remove up down keys on salary fields

- frontend/components/StarRating.vue
- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/165041524-7ab212f5-68a4-4b27-86da-79de31d79683.mp4
> Add the scrool when empty

- frontend/pages/add_salary.vue
> Change form welcome message

- frontend/components/Company.vue
- frontend/components/StarRating.vue
- frontend/pages/add_salary.vue
> Apply border radius to table

- frontend/components/StarRating.vue
- frontend/pages/add_salary.vue
> Add footer

- frontend/components/Select.vue
- frontend/pages/add_salary.vue
> Remove bottom contributon page

- frontend/components/Select.vue
> Bring back the Company filter

- frontend/pages/index.vue
> center align text

- backend/internal/storage/companies.go
- backend/internal/storage/ratings.go
This pull request escape raw query to avoid sql injection
- run `make docker-e2etest`
> escape raw query

- frontend/components/StarRating.vue
- frontend/layouts/app.vue
- frontend/pages/index.vue
https://user-images.githubusercontent.com/34966088/166102676-a5a91836-fd34-4b1b-af79-ae4493f6e023.mp4
> Logo should have the same behavoir on all pages

- frontend/pages/index.vue
> Left align buttom text at the edge

- frontend/components/StarRating.vue
- frontend/pages/index.vue
https://user-images.githubusercontent.com/34966088/166102458-66083dae-9230-460d-9be2-2519e95bb7a9.mp4
> Change cursor to a pointer rating stars

- frontend/components/Company.vue
- frontend/components/StarRating.vue
- frontend/layouts/app.vue
- frontend/pages/index.vue
https://user-images.githubusercontent.com/34966088/166105565-a3d47d29-88c7-41af-bc75-e6129a7c4044.mp4
> Add info icon

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/166108495-276dc7f6-e6bc-4237-ab6f-b4ef51fb956d.mp4
> Formatting tooltips

- frontend/components/Select.vue
- frontend/store/cities.js
- frontend/store/index.js
This pull request add the list of city in the dropdown filter cities
Why ?
it gives users the possibility to filter their result on cities
no screen is available right now because the stage backend is down
> Citiy filter

- frontend/components/Company.vue
> Factoring format date

- frontend/components/Select.vue
- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/166134440-f2f621e1-5f46-4338-ac73-3e95b3562348.mp4
> Display cursor when it is on focus

- frontend/components/Select.vue
> Adjust the length of filters

- frontend/components/Select.vue
- frontend/pages/add_salary.vue
> fix: few typos

- frontend/components/Company.vue
This pull request fix a typos issue(rename undefine to undifined)
> fix-typo: rename undefine to undifined in the Company component

- frontend/pages/add_salary.vue
> Update company name tittle description

- backend/e2etests/ratings.test.after.js
- backend/e2etests/ratings.test.js
- backend/fixtures/postgres/sql/salaries.sql
- backend/internal/storage/companies.go
- backend/internal/storage/ratings.go
This pull request does only show ratings with 3 entry for the same jobtitle and the same company when the company filter is apply
Why ?
Because people can just make a request with the company name and see all the record for the company
-  run make start-postrges to run an initialized database
1️⃣Add a rating for Elhmnco company
```shell
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Elhmnco","job_title": "Dev","rating": 2,"salary": 1200,"seniority": "CV"}'
```
```json
{"message":"created"}
```
2️⃣Get list of ratings 
```shell
curl -s -X …
```
> Only show companies when filters are alright

- frontend/pages/add_salary.vue
https://user-images.githubusercontent.com/34966088/169399697-cd40c6a5-2485-4bd6-a46b-46a4a83eaea9.mp4
> Realtime thousand separators

- frontend/components/Footer.vue
> feat: make the footer date dynamic

- frontend/components/Average.vue
> feat: align the elements of the last line

- backend/e2etests/job_offers.test.js
- backend/e2etests/package-lock.json
- backend/internal/handlers/job_offers_handler.go
- backend/internal/storage/job_offers_db.go
- backend/internal/storage/jobtitles.go
- backend/internal/storage/ratings.go
- backend/main.go
- backend/migrations/20211019221200_init_db.sql
- backend/pkg/models/v1beta/job_offers.go
- run make start-postgres to run an initialized database
- then run the following commands
1️⃣ POST Job offer
```shell 
curl -s -X POST '{ "email": "oss-cm@gmail.com", "company_name": "Gamesmania", "job_title": "Frontend Dev", "is_remote": true, "description": " Oss is hiring a Remote Go Backend Engineer \n Remote - We are looking for a backend engineer who can work 30+ hr/weekOur ideal candidate has:- 1+ years experience writing in Go: $70,000 — $120000/year", "how_to_apply": "", "apply_url": "", "apply_email_address": "oss-cm@gmail.com" }'
```
```json
{
"id": 1,
"createdat": "2023-01-29T09:48:59.4477866+01:00",
"updatedat": …
```
> feat: post a job offer - backend

- frontend/README.md
This pull request update the frontend's README.md
> frontend: update README

- frontend/components/Average.vue
https://user-images.githubusercontent.com/34966088/219378913-8d99297b-850b-4897-81a0-81a638f52519.mp4
> add a loading text while the database is loading info in the background

- backend/docs/companies.go
- backend/docs/company_ratings.go
- backend/docs/ratings.go
- backend/docs/salaries.go
- backend/go.mod
- backend/internal/config/config.go
- backend/internal/handlers/cities_handler.go
- backend/internal/handlers/companies_handler.go
- backend/internal/handlers/company_ratings_handler.go
- backend/internal/handlers/job_offers_handler.go
- backend/internal/handlers/jobtitles_handler.go
- backend/internal/handlers/ratings_handler.go
- backend/internal/handlers/salaries_handler.go
- backend/internal/handlers/seniority_handler.go
- backend/internal/server/server.go
- backend/internal/storage/cities.go
- backend/internal/storage/companies.go
- backend/internal/storage/company_ratings.go
- backend/internal/storage/job_offers_db.go
- backend/internal/storage/jobtitles.go
- backend/internal/storage/ratings.go
- backend/internal/storage/salaries.go
- backend/main.go
- backend/swagger.yaml
We need to remove `elhmn` from the package imports
> Change elhmn to osscameroon for package import

- backend/migrations/20211019221200_init_db.sql
- backend/migrations/20230401110139_create_job_offers_table.sql
Create a new migration file for job offers
Why ?
To prevent crash on production database
How ?
Create another migration file for the job_offers table creation
move to the backend folder with cd ./backend
run the command `make docker-e2etest`
> Create a new migration file for job offers

- backend/docs/companies.go
- backend/docs/company_ratings.go
- backend/docs/ratings.go
- backend/docs/salaries.go
- backend/e2etests/subscribers.test.after.js
- backend/go.mod
- backend/internal/config/config.go
- backend/internal/handlers/cities_handler.go
- backend/internal/handlers/companies_handler.go
- backend/internal/handlers/company_ratings_handler.go
- backend/internal/handlers/job_offers_handler.go
- backend/internal/handlers/jobtitles_handler.go
- backend/internal/handlers/ratings_handler.go
- backend/internal/handlers/salaries_handler.go
- backend/internal/handlers/seniority_handler.go
- backend/internal/handlers/subscribers_handlers.go
- backend/internal/server/server.go
- backend/internal/storage/cities.go
- backend/internal/storage/companies.go
- backend/internal/storage/company_ratings.go
- backend/internal/storage/job_offers_db.go
- backend/internal/storage/jobtitles.go
- backend/internal/storage/ratings.go
- backend/internal/storage/salaries.go
- backend/internal/storage/subscribers.go
- backend/main.go
- backend/migrations/20230401115114_create_job_subscribers_table.sql
- backend/pkg/models/v1beta/subscribers.go
Create subscribers post endpoints related to #384 
move to the backend folder with cd ./backend
run `make start-postrges` to run an initialized database
run `make run` to launch the api
then run the command
1️⃣ POST Valid subscriber
```shell 
curl --location 'http://localhost:7000/subscribers' -s -X POST '{ "email": "oss-cm@gmail.com"}'
```
```
{
"id": 2,
"email": "ossdevs-cm@gmail.com",
"createdat": "2023-04-01T00:00:00Z",
"updatedat": "2023-04-01T00:00:00Z"
}
```
2️⃣ POST subscriber with empty email
```shell 
curl --location 'http://localhost:7000/subscribers' -s -X POST '{ "email": ""}'
```
```
{
"error": "email is not a valid email address"
}
```
3️⃣ POST subscriber with invalid email
```shell …
```
> Create subscribers post endpoints

- .github/workflows/backend-build-api-image.yaml
> core: update deploy branch to use actions/checkout@v3

- frontend/components/JobPost.vue
- frontend/pages/index.vue
> feat: change format date

- frontend/components/JobPost.vue
- frontend/components/SubmitModal.vue
- frontend/pages/add_job.vue
- frontend/pages/index.vue
https://github.com/osscameroon/jobsika/assets/34966088/49ed42d8-ea11-4223-b50e-3c46b224c8df
> Fix tooltip bug

- frontend/components/JobPagination.vue
- frontend/components/Pagination.vue
This pull request fix the problem that occurs when changing the page in on jobs and salaries pages
https://github.com/osscameroon/jobsika/assets/49993443/ab9f2b4c-2927-4ddb-920e-89f365adb25c
> Fix pagination

- frontend/pages/add_job.vue
- frontend/pages/confirm_job.vue
- frontend/store/index.js
- frontend/store/jobs.js
This pull request adds the possibility to edit a job offer after seeing the preview
https://github.com/osscameroon/jobsika/assets/49993443/c97c38ee-4418-4fd7-a0cd-3f8e8c263f3e
>  Add the possibility to edit a job offer after seeing the preview

- frontend/pages/confirm_job.vue
- frontend/pages/payment_instruction.vue
- frontend/store/index.js
- frontend/store/jobs.js
This create the payment link after the job have been posted and allow the `process payment` button to redirect the user to the payment on open collective.
https://github.com/osscameroon/jobsika/assets/49993443/452d1227-7f19-49cd-9e2a-b2686c645480
> Payment link for job
