- backend/e2etests/seniority.test.js
- backend/internal/handlers/seniority_handler.go
- backend/main.go
- backend/pkg/models/v1beta/salaries.go
This pull request add a seniority endpoint
- then run the command curl -X GET --silent localhost:7000/seniority you should see something like this
```
["Entry-level","Mid-level","Senior","Above senior-level","Executive"]
```
> feat: add seniority endpoint

- backend/e2etests/salaries.test.js
- backend/internal/handlers/salaries_handler.go
- backend/internal/storage/salaries.go
- backend/main.go
This pull request add the GET `salaries/id` endpoint
- then run the command `curl -X GET localhost:7000/salaries/1` you should see something like this
```
{"id":1,"title":"Recruiting Manager","salary":1624669,"seniority":"Seniority","city":"Livefish","company_id":994,"createdat":"0001-01-01T00:00:00Z","updatedat":"0001-01-01T00:00:00Z"}
```
> feat: add get salaries by id endpoint

- backend/e2etests/companies.test.js
- backend/internal/handlers/companies_handler.go
- backend/internal/storage/companies.go
- backend/main.go
This pull request add the GET `companies/id` endpoint
- then run the command `curl -X GET localhost:7000/salaries/1` you should see something like this
```
{"id":1,"name":"Brainverse","rating":2,"createdat":"0001-01-01T00:00:00Z","updatedat":"0001-01-01T00:00:00Z"}
```
> feat: add GET companies/:id endpoint

- backend/docs/jobtitles.go
- backend/e2etests/jobtitles.test.js
- backend/internal/handlers/jobtitles_handler.go
- backend/internal/storage/jobtitles.go
- backend/main.go
- backend/swagger.yaml
This pull request add the GET `jobtitles` endpoint
- then run the command `curl -X GET localhost:7000/jobtitles` you should see something like this
```
["Account Coordinator","Account Executive","Account Representative I","Account Representative II","Account Representative III","Account Representative IV","Accountant I","Accountant II","Accountant III","Accountant IV"
...
]
```
> Add get jobtitles endpoint

- backend/e2etests/companies.test.js
- backend/internal/storage/companies.go
This pull request sorts GET `companies` endpoint response list
- then run the command `curl -X GET localhost:7000/companies` you should see something like this
```
[{"id":724,"name":"Abata","rating":5,"createdat":"0001-01-01T00:00:00Z","updatedat":"0001-01-01T00:00:00Z"},{"id":512,"name":"Abatz","rating":1,"createdat":"0001-01-01T00:00:00Z","updatedat":"0001-01-01T00:00:00Z"},...
]
```
> Sort list of companies

- backend/docs/ratings.go
- backend/e2etests/ratings.test.js
- backend/internal/handlers/ratings_handler.go
- backend/internal/storage/ratings.go
- backend/main.go
- backend/pkg/models/v1beta/ratings.go
- backend/swagger.yaml
This pull request add the GET `average-salary` endpoint
- then run the command `curl -X GET localhost:7000/average-rating` you should see something like this
```
{"rating":3,"salary":2543437}
```
> Add average-salary get endpoint

- backend/docs/ratings.go
- backend/e2etests/ratings.test.js
- backend/internal/storage/ratings.go
- backend/pkg/models/v1beta/ratings.go
- backend/swagger.yaml
This pull request add a `createdAt` field to the `/ratings` `GET` endpoint response list
- then run the command `curl -X GET localhost:7000/ratings` you should see something like this
```
[
{"salary_id":1,"company_id":994,"company_rating_id":569,"rating":2,"salary":1624669,"company_name":"Realbridge","seniority":"Seniority","comment":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","job_title":"Recruiting Manager","country":"Country","city":"Livefish","createdat":"00 …
```
> Add creation date to /ratings GET endpoint response

- backend/docs/ratings.go
- backend/e2etests/ratings.test.js
- backend/internal/handlers/ratings_handler.go
- backend/internal/storage/ratings.go
- backend/pkg/models/v1beta/ratings.go
- backend/swagger.yaml
This pull request implement pagination for the GET `ratings?page=<page_number>&limit=<limit>` endpoint response list
- then run the command `curl -X GET localhost:7000/ratings?page=3&limit=20` you should see something like this
```
{
"hits": [
{
"salary_id": 41,
"company_id": 949,
"company_rating_id": 747,
"rating": 2,
"salary": 636974,
"company_name": "Vimbo",
"seniority": "Seniority",
"comment": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
"job_title": "Safety Technician I",
"country": "Country",
"city": "Feednation",
"createdat": "0001-01-01T00:00:00Z"
},
...
],
"limit": 20, …
```
> Add pagination ratings endpoints

- backend/e2etests/ratings.test.js
- backend/internal/handlers/ratings_handler.go
- backend/internal/storage/ratings.go
This pull request implement filters for the GET `ratings?company=<company_name>&jobtitle=<job_title>` endpoint response list
- then run the command `curl -X GET localhost:7000/ratings?jobtitle=Recruiting%20Manager` you should see something like this
```
{
"hits": [
{
"salary_id": 1,
"company_id": 994,
"company_rating_id": 569,
"rating": 2,
"salary": 1624669,
"company_name": "Realbridge",
"seniority": "Seniority",
"comment": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis …
```
> Implement filters

- backend/docs/ratings.go
- backend/e2etests/ratings.test.js
- backend/internal/handlers/ratings_handler.go
- backend/internal/storage/ratings.go
- backend/swagger.yaml
This pull request implements average rating with filters for the GET `average-rating?company=<company_name>&jobtitle=<job_title>` endpoint response list
- then run the command `curl -X GET localhost:7000/average-rating?company=Realbridge&jobtitle=Recruiting%20Manager` you should see something like this
```
{"rating":2,"salary":1624669}
```
> Compute average ratings with filters

- frontend/components/Average.vue
- frontend/components/Company.vue
- frontend/nuxt.config.js
- frontend/plugins/filters.js
This pull request is for adding thousand separator on salaries like mentioned in issue #107
Why ?
To make salaries more readable.
How ?
Just by separating thousands by a comma.
Just by checking the screenshots below :
> feat: adding a thousand separator on salaries

- frontend/plugins/filters.js
This pull request removes the regular expression from the thousands separator filter (see #119).
Why ?
Because regex have unpredictable side effects
How ?
Using the native `Intl.NumberFormat`.
Check the Salaries table, column Salary.
> refactor: remove regex from thousands separator filter

- frontend/pages/index.vue
> TypoOnTheSubTitle: put the word rating in the plural

- backend/e2etests/companies.test.js
- backend/internal/storage/companies.go
This pull request set default values for the `GET /companies` endpoint
- run `make start-api` to start the api
- then run the command `curl -X GET localhost:7000/companies | jq` you should see something like this
```
{
"hits": [{
"id": 102,
"name": "ADC",
"rating": 0,
"createdat": "2022-04-06T00:00:00Z",
"updatedat": "2022-04-06T00:00:00Z"
},
{
"id": 103,
"name": "ADER",
"rating": 0,
"createdat": "2022-04-06T00:00:00Z",
"updatedat": "2022-04-06T00:00:00Z"
},
...
],
"limit": 20,
"nbHits": 1000,
"offset": 40
}
```
> Add default values to the get companies and endpoint

- backend/e2etests/ratings.test.after.js
- backend/e2etests/ratings.test.js
- backend/internal/storage/ratings.go
This pull request hide company name, company id, rating and comment when fetch ratings(`GET /ratings`) if it has not more than 5 users having set their salaries. (Related to #128 )
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Companyrating","job_title": "Cleaner","rating": 2,"salary": 1200,"seniority": "CV"}'
```
```
{"message":"created"}
```
You can see that the entry with `curl -s -X GET "http://localhost:7000/ratings?page=1&limit=200&company=Companyrating"`
The …
> Hide company name, company id, rating and comment if it has not more than 5 users having set their salaries

- backend/e2etests/ratings.test.after.js
- backend/internal/handlers/ratings_handler.go
- backend/pkg/models/v1beta/ratings.go
This pull request set Jobtitles and City as Mandatory fields for the rating POST request. Related to #202 
- run make start-postgres to run an initialized database
- then run the following commands
1️⃣ Check JobTitle
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "OssCameroun","job_title": "","rating": 2,"salary": 1200,"seniority": "CV"}'
```
```
{"error":"job title is mandatory"}
```
2️⃣ Check City
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "","comment": "my comment","company_name": …
```
> feat(backend): set job title and city as mandatory fields for the rating POST request

- backend/e2etests/ratings.test.after.js
- backend/internal/storage/ratings.go
This pull request hides the company name, company id, rating, and comment when fetch ratings(`GET /ratings`) if it has not more than 3 users having set their salaries.
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Companyrating","job_title": "Cleaner","rating": 2,"salary": 1200,"seniority": "CV"}'
```
```
{"message":"created"}
```
You can see that the entry with `curl -s -X GET "http://localhost:7000/ratings?page=1&limit=200&company=Companyrating"`
The output should be …
> feat: change set the number of entry with the same company and job title before we can display and return it to users

- backend/internal/handlers/seniority_handler.go
Add `Intern` as a possible seniority
- run `make start-postgres` to run an initialized database
- then run the command `curl -X GET localhost:7000/seniority` you should see something like this
```
["Intern","Entry-level","Mid-level","Senior","Above senior-level","Executive"]
```
> feat: add seniority intern

- backend/e2etests/ratings.test.js
- backend/internal/storage/ratings.go
This pull request do not consider ratings equal to 0 when calculating the average rating
- 
1️⃣then run the command to create a ratings
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Oss","job_title": "Dev","rating": 2,"salary": 1200,"seniority": "CV"}'
```
2️⃣run the following command to get the average rating
```shell 
curl -s -X GET "http://localhost:7000/average-rating?company=Oss"
```
```json
{
"rating": 2,
"salary": 1200
}
```
3️⃣ now run this command x times to create company rating with rating == 0 …
> feat(backend): do not consider ratings == 0 , when calculating the average rating

- backend/e2etests/ratings.test.js
- backend/internal/storage/companies.go
This pull request does list only company with salary entries not between 1 and maxEntryBeforeDisplay-1.
Why ?
Because we need to not hide company if a we hasn't maxEntryBeforeDisplay entries. See #197 and this [comment ](https://github.com/osscameroon/camerdevs/issues/197#issuecomment-1107782063)
1️⃣Add a rating for a company
```shell 
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Elhmnco","job_title": "Cleaner","rating": 2,"salary": 1200,"seniority": "CV"}'
```
```json …
```
> fix(backend): only show list of company with salary entries not between 1 and maxEntryBeforeDisplay-1

- backend/e2etests/ratings.test.js
- backend/internal/handlers/ratings_handler.go
- backend/internal/storage/ratings.go
This pull request add seniority filter on Get Ratings
- run make start-postgres to run an initialized database
- then run the following commands
1️⃣ Get ratings of a city
```shell 
curl -X GET 'http://localhost:7000/ratings?page=1&limit=10&seniority=Seniority'
```
you should see every entry with seniority equal to Seniority
> feat: add seniority filter on Get Ratings

- .gitignore
- README.md
- backend/Makefile
- backend/docs/companies.go
- backend/docs/company_ratings.go
- backend/docs/docs.go
- backend/docs/ratings.go
- backend/docs/salaries.go
- backend/go.mod
- backend/internal/config/config.go
- backend/internal/handlers/cities_handler.go
- backend/internal/handlers/companies_handler.go
- backend/internal/handlers/company_ratings_handler.go
- backend/internal/handlers/jobtitles_handler.go
- backend/internal/handlers/ratings_handler.go
- backend/internal/handlers/salaries_handler.go
- backend/internal/handlers/seniority_handler.go
- backend/internal/server/server.go
- backend/internal/storage/cities.go
- backend/internal/storage/companies.go
- backend/internal/storage/company_ratings.go
- backend/internal/storage/jobtitles.go
- backend/internal/storage/ratings.go
- backend/internal/storage/salaries.go
- backend/main.go
- backend/swagger.yaml
- docs/how-to-add-a-new-table.md
- frontend/components/Footer.vue
Replaces all occurrences of `camerdevs` by `jobsika`.
The `./.github/workflows/backend-build-api-image.yaml` was excluded in purpose as editing this file would have broken the deployment.
> chore: replace `camerdevs` by `jobsika`

- frontend/components/Select.vue
Adds `All seniorities` to seniority filter
Why ?
To match the other filters
How ?
Added a new option in the corresponding select in `components/Select.vue`
Display the home page.
I also took the opportunity to set the same width for all the filters on desktop.
Should close #307
> fix: add all seniorities to seniority filter

- frontend/components/Company.vue
Align table titles with corresponding items
Why ?
To give a better visual.
How ?
Changed the horizontal padding of `th` from `px-6` to `px-4`
Display the home page.
Should close #302
> Align table titles with corresponding items

- frontend/components/Title.vue
- frontend/tailwind.config.js
Issue : https://github.com/osscameroon/jobsika/issues/326
This pull request updates tooltip's color from grayC to grayDark
Why ?
It's not very visible. The first time I used the site, I didn't see it then I decided to do a PR in order to add a dark gray color more visible. Then, the user will easily click on this tooltip to get the extra information.
How ?
I added grayDark color in tailwind.config.js then I used that in Title.vue
Just compare the visibility before and after this change. This color is a dark one so it is easy for the user to pay attention on this detail.
Screenshots:
Before
After
> Update tooltip color from gray c to dark gray

- backend/e2etests/ratings.test.js
- backend/internal/storage/ratings.go
This pull request hide entry who do not satisfy the maxEntryBeforeDisplay rules when calculating average-rating for a given  company.
1️⃣Add a rating for Ossco company
```shell
curl -s -X POST 'http://localhost:7000/ratings' -H 'Content-Type: application/json' -d '{"city": "Douala","comment": "my comment","company_name": "Ossco","job_title": "Dev","rating": 5,"salary": 1200,"seniority": "CV"}'
```
```json
{"message":"created"}
```
2️⃣Get average-rating of Ossco
```shell
curl -s -X GET "http://localhost:7000/average-rating?company=Ossco"
```
you should see  👇
```json
{
"rating": …
```
> Don't calculate average ratings for hidden companys data

- backend/Dockerfile
- backend/docker-compose.yml
When running api, using docker swarm on linux the graphql calls failed with the following error:
```
time="2023-05-29T08:33:45Z" level=error msg="Post \"https://opencollective.com/api/graphql/v2\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
I suspect that it has something to with the ca-certificates on linux. I then followed the instructions from
https://github.com/google/go-github/issues/1049#issuecomment-454446363 and hope it will solve our issue
> backend: update the ca-certificates
